### ISSUE TITLE
Add more to template landing page

### ISSUE THREAD

**Issue by r-ford** [ProjectPythiaTutorials/cookbook-template#10]
I think we should add more structure to the [template landing page](https://github.com/ProjectPythiaTutorials/cookbook-template/blob/main/notebooks/landing-page.md), based on the [Radar Cookbook's landing page](https://github.com/ProjectPythiaTutorials/radar-cookbook/blob/main/notebooks/landing-page.md). Requiring at least motivation/background and structure/outline sections would give cookbooks some consistency.

**Comment by ktyle** [comment]
Currently, the README.md and the notebooks/landingpage.md in the Radar Cookbook are essentially the same, aside from the former's build-book and link-checker badges. Should we distinguish the content between these two files ... or perhaps trim down the README.md, replacing the descriptive text that is repeated in the landing page with a link to the landingpage (maybe with some "pithy" text as well)?

**Comment by r-ford** [comment]
That makes sense to me. I'm currently using the README.md as a place to put the Contributor's Guide, but I'll move it to its own file. In the guide, I can direct the contributor to replace the template's README.md with a title, the badges, a sentence or two about the cookbook (like it is in the Radar Cookbook before the Motivation section), and a link to the landing page.
