### ISSUE TITLE
Little typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by erogluorhan** [ProjectPythiaTutorials/cookbook-template#27]
In step 2.ii, the command needs to be:

`conda env create -f <your-cookbook-name>-dev.yml`

instead of 

`conda env create -f environment.yml`

as we suggest renaming the file in the previous step.

**Comment by r-ford** [comment]
The current wording is confusing, but I meant change [`name:` within the environment file](https://github.com/ProjectPythiaTutorials/cookbook-template/blob/main/environment.yml) but keep the name of the file as `environment.yml`.

**Comment by brian-rose** [comment]
Yes, I think we're trying to keep all environment file names as environment.yml in part so theres less customization necessary in the GitHub actions for each cookbook repo

**Comment by erogluorhan** [comment]
Oh, these clarify! Closing then.
