### ISSUE TITLE
`deploy-book` failing

### ISSUE THREAD

**Issue by r-ford** [ProjectPythiaTutorials/cookbook-template#9]
I made a test PR on the [cookbook I'm working on](https://github.com/r-ford/cmip6ohu-cookbook), and the `deploy-book` action is failing with this error:
```
Error: no matching workflow run found with any artifacts?
```
It looks like it is also failing in [this template](https://github.com/ProjectPythiaTutorials/cookbook-template/runs/7009790788) and the [radar cookbook](https://github.com/ProjectPythiaTutorials/radar-cookbook/runs/6971598476), so it's probably related to #7.

**Comment by r-ford** [comment]
It looks like [`deploy-book` was failing 14 days ago](https://github.com/ProjectPythiaTutorials/radar-cookbook/actions/runs/2476328877), so that's before #7 was merged.

**Comment by brian-rose** [comment]
I just enabled debug logging for the actions in this repository, following https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging

Opening up a new PR #15 to see if I can learn more about what's going on.

**Comment by brian-rose** [comment]
Looks like #16 has resolved the problem!

I will turn off the debug logging and close this issue. I'll also work on back-porting these updates to the [radar cookbook](https://github.com/ProjectPythiaTutorials/radar-cookbook)
